// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skzmagfijakakoxprgzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrem1hZ2ZpamFrYWtveHByZ3piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjU5MjcsImV4cCI6MjA2MzkwMTkyN30.N5KOTL-sME1oLYpm6KtFsmon7dFpnUxAioQSnE1axQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);